### ISSUE TITLE
Cant unpack

### ISSUE THREAD

**Issue by JotaVexD** [BenBeri/BlockadeSim#2]
When using obsidio and server, cant compile or run. You guys are using eclipse with gradle for coding and run the game? If yes why got so many errors on project?

**Comment by mdjong1** [comment]
You sure you included all necessary jars and are running in the right jre version?

**Comment by JotaVexD** [comment]
Which version u guys are using?

I get obsidio, and using in a gredle project on eclipse. That's the right way?

After this many error show up on core.

**Comment by mdjong1** [comment]
I have these added to get everything to work. Admittedly, there's a few too many. 

![image](https://user-images.githubusercontent.com/4410453/34852452-02454950-f72f-11e7-98d9-bcc22fafdea9.png)

**Comment by JotaVexD** [comment]
![2018-01-11_21-48-23](https://user-images.githubusercontent.com/1613811/34853104-2e3fd09a-f719-11e7-9df4-1fddb5a3039b.png)
 U know why i stay getting this?

**Comment by mdjong1** [comment]
In run configuration, go to arguments, then working directory and set it to your main folder (which has core/assets/sea/cell.png). Then it'll be able to correctly find the files

**Comment by JotaVexD** [comment]
Now dont show any error but system open and close xD

**Comment by JotaVexD** [comment]
![2018-01-11_22-03-56](https://user-images.githubusercontent.com/1613811/34853519-556541da-f71b-11e7-88d0-9ad44f480386.png)
I'm getting this warnings

**Comment by mdjong1** [comment]
Well... Does it run though?

**Comment by mdjong1** [comment]
Right, well, I think if you can't figure out how to run this by now you're kind of on your own..

**Comment by JotaVexD** [comment]
?

**Comment by JotaVexD** [comment]
Sorry. I see the eclipse have a bug with switch. But I rly dont get how to repair this. And dont get what is the "This" on switch.

**Comment by JotaVexD** [comment]
I got the game running. At last can explain to me how server work please?
